app/controllers/admin/members_controller.rb
app/models/member.rb
app/views/admin/members/index.html.haml

Fixes #489.
This PR will add a more basic pagination parameter for the search results, containing only 'next' and 'previous' buttons.
Also fixes an issue that caused the pagination numbers to render inside the column for the limit dropdown.

Fix crash when searching for Members

---

.dev-database-conf/custom-overrides.cnf
.rbenv-vars-sample
INSTALLING.md
config/database.yml
config/locales/nl.yml
docker-compose.yml

This PR adds setup and instructions to run the development database in a Docker container, and expands the install guide.
The Docker setup was added in response to concerns that the database setup was too hard, and to prevent problems from occurring due to a mismatch between the MariaDB version used in development and the version on the server.
The new Docker setup is __not required__, and is intended to not interfere with a possibly existing MariaDB on the host by using a nonstandard port.
CC @Riscky

Use Docker for the development database, update install guide

---

app/assets/javascripts/admin/payments.js

The name of the `hidden` attribute was changed to `d-none` with Bootstrap 4, but wasn't updated in our code.
This fixes the payments page not filtering when a member's name is typed.

Fix filtering members on payments page

---

app/models/activity.rb

Fixes #488 
Extra notes are now required if either public or mandatory is checked.
The seeds seem to already take this into account and won't have nonexistent mandatory notes.

Require notes if public or mandatory is checked

---

app/controllers/users/password_change_controller.rb
app/views/members/home/edit.html.haml
app/views/user/password/edit.html.haml
config/locales/en.yml
config/locales/nl.yml
config/routes.rb

Fixes #393 
Members can now change their password through the member edit page instead of having to click "forgot password".

Add change password option for members

---

Gemfile.lock

[Changelog](https://github.com/nesquena/rabl/blob/master/CHANGELOG.md#0142-september-10th-2019)
rabl 0.14.1 is not compatible with rails 6 so everything using rabl templates (mainly the API) is broken.
After updating to 0.14.2 the templates work as expected.

Bump rabl from 0.14.1 to 0.14.2

---

app/controllers/admin/home_controller.rb

Fixes #507 
Added a additional query to check if activities are before the current time.

Fix future outstanding payments

---

app/assets/stylesheets/admin/activities.css
app/views/admin/activities/partials/_edit.html.haml
app/views/admin/home/index.html.haml

Removed 4 collumn layout for admin home page shortcuts
This was giving problemns on screensizes between 1200px and 1600px
Blame Bootstrap for not adding an xxl screen size

WIP: fixed zoom problems

---

app/views/members/home/edit.html.haml

I noticed the privacy statement on the member page still displayed the old one hosted on old.svsticky.nl. I updated it to the most recent Dutch one. There's a more recent statement, but that one's in English. If we would prefer to use that one, please let me know.

Update URL of privacy statement

---

app/views/layouts/members.html.haml

Accidentally removed the sign out button for mobile phones when I added the external links.

Readded signout button

---

docker-compose.yml

Adds Redis to the docker-compose. db:setup needs this now, which caused the old version to fail as redis was not present.

Fix db:setup in local koala

---

app/views/members/home/edit.html.haml
config/routes.rb

Closes #587 
For some reason rails keeps overwriting the _method field with a token on refresh even with authenticity_token: false.
By using post the _method field is no longer required and can't be overwritten.

Fix member edit form breaking on refresh

---

app/models/member.rb
test/models/member_test.rb

Because some studentID's can't be validated with the elfproef I removed this check from Koala.

Removed the 'Elfproef' from the studentID validity check.

---

app/views/admin/members/show.html.haml
config/locales/admin.en.yml
config/locales/admin.nl.yml

On the admin side there was an untranslated string above the mailchimp interests list.
Additionally, a message is now displayed when a member doesn't exist in mailchimp.

Add message for members not in mailchimp, add missing translation

---

app/controllers/admin/members_controller.rb
app/controllers/members/home_controller.rb

Closes #746 
When someone signs up they are automatically added to mailchimp.
Some old users don't exist in mailchimp, these can be manually added if necessary.
Once they have been added, their interests will become visible on the show and edit views and they will be synchronized with mailchimp.
This PR stops the synchronization attempts for members who don't exist in mailchimp.

Fix member update if member is not in mailchimp

---

app/controllers/members/home_controller.rb
app/views/members/home/edit.html.haml

Closes #745 
The strings passed to `flash` are now always translated before they are passed.

Make method of flash translation consistent

---

app/assets/javascripts/admin/members.js
app/assets/stylesheets/admin/activities.css
app/controllers/admin/members_controller.rb
app/controllers/api/checkout_controller.rb
app/views/admin/members/show.html.haml
config/locales/admin.en.yml
config/locales/admin.nl.yml
config/locales/checkout.en.yml
config/locales/checkout.nl.yml
config/routes.rb
db/migrate/20210309155656_add_disabled_to_checkout_cards.rb
db/schema.rb

Closes #453 
Adds a new table (card) to the member overview, in which the member's cards can be seen. 
For each card, the UUID is shown and its status next to that.
From this overview, you can:
- Activate cards that have not been activated yet
- Deactivate cards
- Reactivate deactivated cards

Disable NFC cards

---

app/views/admin/settings/logs.html.haml

When the user deletes their account the impressionist page tries to query the user but fails and makes the entire page fail. This should fix it.

Query for non-existent user after destroy

---

app/assets/stylesheets/doorkeeper.css
app/javascript/stylesheets/doorkeeper.scss
app/views/devise/confirmations/new.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/doorkeeper/authorizations/new.html.haml
app/views/doorkeeper/authorizations/show.html.haml
app/views/layouts/doorkeeper.html.haml
app/views/layouts/partials/_footer.html.haml
config/webpacker.yml
postcss.config.js
tailwind.config.js

This completely removes Bootstrap from the Doorkeeper pages, replacing everything with Tailwind.
Also, it adds a beautiful dark theme for this pages.
I'm not a designer, suggestions for improvements are welcome.
There is a bit of duplication in the code, but it has been there for a while, so I'm not fixing it in this PR.
Someone should DRY up the different Doorkeeper / Devise screens however.
I removed the Yeti colors in favor of the default Tailwind colors.
This set of colors is just more complete (and I don't really care about Yeti's feelings).
Also included is a bit of Webpack config changes that I came across while developing.
TODO: 
This is how the new dark theme looks like:

Darktheme login

---

docker-compose.yml

The postgres version in the docker compose file was unpinned, while this is not an issue right now, it will be when docker sees 14 as the latest.

FIX: Pin docker compose version to 13

---

config/application.rb
config/environments/development.rb

schema_format was only set for development. This should be set for all environments

Schema format for application.rb

---

.github/workflows/build.yml

Due to the release of Nix 2.4 (see svsticky/sadserver/issues/333), and the fact that the install-nix-action just updates Nix without warning, we need to pin the version of Nix in CI for the time being.

Pin nix to version 2.3 to keep builds from failing

---

nix/node_modules.nix
package.json
tailwind.config.js

Now with JIT as default mode, and the purge/content config doesn't need the custom defaultExtractor anymore to work.

Update tailwindcss to version 2 to 3

---

app/models/activity.rb
app/views/admin/activities/partials/_edit.html.haml

The "is_enrollable" checkmark now gets automatically checked when an activity opens. This checkmark can then be unchecked to close the activity again. Checking the "is_enrollable" checkmark before the activity is opened, will remove the open date and time and open up the activity.
Creating an activity with both an open date and time and the "is_enrollable" checkmark will also remove the open date and time and open the activity for enrollement. Perhaps an error should be given to warn the creator instead?

Checkmark consistency and overrides for enrollable date

---

app/models/activity.rb
app/views/admin/activities/partials/_edit.html.haml

This should fix issue #940 by checking if the start_time is present before reading its value.
While debugging the issue I came across a related issue that also has been fixed.

activity edit: check if start_time is present before reading its value

---

app/javascript/src/lib/mail.js

This should fix #942 by disabling the send button when no recipients are selected.
The section has been completely rewritten to be more readable.

Rewrite email dropdown code

---

README.md
app/controllers/admin/payments_controller.rb
app/controllers/admin/settings_controller.rb
app/controllers/members/home_controller.rb
app/controllers/members/payments_controller.rb
app/javascript/src/members/payments.js
app/models/payment.rb
app/views/admin/payments/index.html.haml
app/views/admin/settings/index.html.haml
app/views/members/payments/index.html.haml
config/app.yml
config/brakeman.ignore
config/locales/admin.en.yml
config/locales/admin.nl.yml
config/locales/en.yml
config/locales/nl.yml
db/seeds/payments.rb
doc/webhook_readme.md
sample.env

Resolves #900,
This removes all references to Payconiq in the codebase (where possible)
This also removes the dropdowns that once showed the choice between Ideal and Payconiq, but are now useless.
This should be tested thoroughly on staging, as test payments cannot go through in development (due to the return address not being reachable by the payment provider).

Payconiq removal

---

config/locales/admin.en.yml
config/locales/admin.nl.yml

This translations were removed in #907, but are still shown on the transactions page.
This is still needed as long as there are Payconiq transactions in the database (which is required by Dutch law for 7 years)

fix missing translation for payconiq_online

---

app/views/members/home/index.html.haml

Fixes #959
I though I fixed this already in #962, but apparently the bug was also present at the members side.

Fix incorrectly formatted time on board posts

---

.github/workflows/build.yml

Currently the CI is instructed to run both on a push and a pull request, which leads to double runs.
This PR prevents that.

prevent the CI from running twice on a PR

---

app/views/layouts/members.html.haml
config/locales/members.en.yml
config/locales/members.nl.yml

Fixes #963
This adds a link to Stickypedia to the members sidebar

add Stickypedia to the members sidebar

---

config/i18n-js.yml

fixes #955 
This instructs `i18n-js` to limit the exported translations to the keys we actually use in javascript.
This doesn't prevent exporting some translations we don't use, but at least limits the size of the file with a factor 50 (1.6M to 34K)

limit export of translations with i18n to actually used ones

---

config/locales/admin.en.yml
config/locales/admin.nl.yml
config/locales/mailings.en.yml
config/locales/mailings.nl.yml

Fixes #929
This updates the payment email and whatsapp text to inform the user of the payment portal.
The exact text is a bit different from the issue, as in email we can use html <a> tags instead of full urls.

update payment email and whatsapp text

---

app/controllers/members/participants_controller.rb
app/javascript/src/members/activities/activities.js
app/javascript/src/members/activities/activity.js

Fixes #964 
This makes it possible for a reservist to unroll from the spares list, even after the unenroll deadline has passed.
This lets the member signal that they don't want to come to this activity, even if extra spaces are available.

make it possible to unenroll after the deadline for reservists

---

.rubocop_todo.yml
app/controllers/admin/checkout_products_controller.rb
app/controllers/admin/group_members_controller.rb
app/controllers/admin/groups_controller.rb
app/controllers/admin/members_controller.rb
app/controllers/admin/participants_controller.rb
app/controllers/admin/posts_controller.rb
app/controllers/admin/settings_controller.rb
app/controllers/api/checkout_controller.rb
app/controllers/api/internal_controller.rb
app/controllers/api/participants_controller.rb
app/controllers/api/webhook_controller.rb
app/controllers/api_controller.rb
app/controllers/members/activities_controller.rb
app/controllers/members/home_controller.rb
app/controllers/members/payments_controller.rb
app/controllers/users/registrations_controller.rb
app/mailers/mailings/checkout.rb
app/mailers/mailings/devise.rb
app/models/activity.rb
app/models/checkout_product.rb
app/models/checkout_transaction.rb
app/models/education.rb
app/models/member.rb
app/models/payment.rb
config/brakeman.ignore
lib/tasks/admin.rake
lib/tasks/doorkeeper.rake

This fixes some rubocop-rails todo's.
The most important of those is that we enable the `DynamicFindBy` cop.
This cop disallows the use of the confusing dynamic `find_by_x` method, in favor for the clearer `find_by x:`.

fix some rubocop-rails todo's

---

app/views/admin/members/new.html.haml

Fixes #978 
`NIL` is undefined, which is why the crash happens (the correct spelling is `nil`).
How this has been undiscovered for 2 years is a bit of a mystery to me.
The extra argument to `options_for_select` isn't needed, so I removed it.

admin/member creation: remove superfluous and undefined NIL parameter

---

config/environments/production.rb
config/environments/staging.rb

We have a lot of log messages that state: `Unknown x-sendfile variation: 'XAccelRedirect'.`
According to the docs, the setting should be spelled with dashes instead (https://guides.rubyonrails.org/asset_pipeline.html#x-sendfile-headers).

set x-accel-redirect correctly

---

app/controllers/members/participants_controller.rb

This solves a bug introduced in #869
It was not possible to enroll without being placed on the spare list for activities without filters.
This has been fixed in this PR.

allow non-sparelist enrolls to filterless activities

---

app/controllers/admin/home_controller.rb
app/models/member.rb
app/views/admin/home/index.html.haml

This makes the definition of defaulters use the payable attribute.
This code is a lot more readable too.

Update the definition of defaulters to align with the payable attribute

---

config/initializers/doorkeeper.rb
config/initializers/doorkeeper_openid_connect.rb

Adds an is_admin claim that lets undead mongoose know whether it should create a superuser or not.

Prepare oauth for undead mongoose

---

INSTALLING.md

INSTALLING.md had some older information about how to set up Koala. For example, the command `bundle exec ./bin/webpack-dev-server` was never mentioned while it is necessary for Koala to run correctly.
In addition, some things were clarified a bit better and the overall flow to run Koala in the future is more explicitly explained.
```
_____     ____
/      \  |  o | 
|        |/ ___\| 
|_________/     
|_|_| |_|_|
My first PR! ^ This is Geoffry.
```

INSTALLING.md is now up-to-date

---

app/javascript/src/members/activities/activity.js
app/views/members/activities/partials/_view.html.haml
vendor/assets/stylesheets/yeti.css.scss

Now, the sign-out color is a more darker (scarier) orange so that the user can easily distinguish signed-in activities from others.
Previously, it was the same default orange used as a warning color.
This idea is brought to you by Jack.

Reservist sign-out button color change

---

app/models/activity.rb

When adding an activity to your calendar through the new link (as mentioned in #1045), the link to the activity is not included in the description of the activity.
I can't run koala locally as of now, but I believe this syntax might be correct. If not, please correct it :)

Activy URL is now displayed in the appointment description

---

.github/workflows/projects.yml

This already happens to issues. Now PR's should be included as well. Not tested, but should work.

Automatically add opened PRs to project

---

app/controllers/admin/participants_controller.rb
app/javascript/src/admin/activities.js
app/views/admin/activities/show.html.haml

Due to whatever reason, the member shows up in the non-reservists table directly after adding them, this is a frontend thing. Refreshing fixes it. LGTM.

Add text field to add a member as reservist to an activity

---

app/views/members/home/index.html.haml

The balance is not correct, and serves no purpose since the decoupling of Mongoose from Koala

Remove mongoose balance from the member home page

---

app/javascript/src/admin/main.js
app/javascript/src/admin/members.js
app/views/admin/members/edit.html.haml

Fix: Dont focus the search bar if the mailer or a textarea is selected
Add: When editing a member, `a` and `ctrl+a` to set the first or second study to 'Afgestudeerd', respectively

More hotkeys

---

app/views/members/activities/partials/_view.html.haml
config/locales/en.yml
config/locales/nl.yml

Add the time an activity sign-up opens to the activities page

---

app/assets/stylesheets/intro.css.scss
app/views/public/home/index.html.haml

The form on the intro page was not set up correctly with bootstrap causing it to lose its margins and be to wide which made the page overflow in the horizontal direction. Furthermore, on very small devices, the greeting header could be to large, making it unreadable and also causing the page to overflow.

Intro form overflow fix

---

sample.env

The empty `KOALA_DOMAIN` variable caused issues in the seeding of the payments, as 'ideal' transactions require this value to be set. This caused the database to be only be seeded with 'pin' transactions.

Removed second empty KOALA_DOMAIN from sample.env

---

db/seeds.rb
db/seeds/activities.rb
db/seeds/groups.rb
db/seeds/members.rb
db/seeds/payments.rb
db/seeds/posts.rb
db/seeds/users.rb

This PR also removes the seeding of Mongoose transactions, but those aren't necessary anymore anyway

Added verbose (failure) logging to the seeding process

---

app/views/layouts/doorkeeper.html.haml

On the login page, in light mode we used the coloured logo, but in dark mode we used the white logo (due to the lack of a white *and* coloured logo). I've added this logo to public.svsticky.nl, and the login page now uses it.

In dark mode, use the coloured logo as well

---

Gemfile
Gemfile.lock
app/controllers/members/payments_controller.rb
app/models/payment.rb
app/views/members/payments/index.html.haml
config/application.rb
gemset.nix
sample.env

Update to Mollie v2 API

---

config/locales/members.en.yml

As per [this](https://svsticky.nl/en-US/vereniging/vertrouwenspersonen) page, the English translation of 'Voel Je Veilig' is 'Feel Safe'.
In my opinion, this should be consistent.

Changed English translation of VoelJeVeilig to 'Feel Safe'

---

app/views/layouts/members.html.haml

trailing / in https://svsticky.nl/discord` routes to a 404, so no viewing discord for you when pressing the discord button on koala.svsticky.nl
pressing the discord button routes you to the discord of sv sticky
remove trailing comma

fixed discord url yay

---

app/controllers/public/home_controller.rb
app/views/public/home/index.html.haml

Basically removes the option to select a bank, which is deprecated.

fix: migrate intro page to new mollie sdk

---

INSTALLING.md
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/routes.rb

Koala was not aware of our new domains, and as such does not accept authentication tokens from those domains.
Starting a local version of those domains should now also be possible.

fix: include other signup domains
