svsticky/constipated-koala

- app/assets/stylesheets/admin/apps.css
> Fix checkout top up layout

- app/views/members/activities/partials/_view.html.haml
- config/locales/en.yml
- config/locales/nl.yml
Added the day of the week to the date notation. This is something that will make the life of our members easier because now they won't have to look up the day of the activity in their calendar.
> Dates with days

- app/assets/stylesheets/admin/checkout_products.css
- app/controllers/admin/checkout_products_controller.rb
- app/models/checkout_product.rb
- app/views/admin/apps/products.html.haml
- app/views/layouts/partials/_navigation.html.haml
- config/locales/en.yml
- config/locales/nl.yml
Fixed how the products page looked after the open source and added some extra functionality based on Bjorn his feedback.
> Improved products page

- Gemfile.lock
- app/assets/javascripts/admin/activities.js
- app/assets/javascripts/admin/apps.js
- app/assets/javascripts/admin/groups.js
- app/assets/javascripts/admin/main.js
- app/assets/javascripts/admin/members.js
- app/assets/javascripts/admin/payments.js
- app/assets/javascripts/admin/settings.js
- app/assets/javascripts/application.js
- app/assets/javascripts/intl_tel_number.js
- app/assets/javascripts/members.js
- app/assets/javascripts/members/activities/activity.js
- app/assets/javascripts/members/main.js
- app/assets/javascripts/toastr.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/members.css
- app/controllers/admin/payments_controller.rb
- app/views/admin/payments/index.html.haml
- app/views/layouts/application.html.haml
- lib/assets/javascripts/mail.js
- package.json
- yarn.lock
Fixes #521
Fixes #532 
The buttons update the payment status but there's no visual indication until the page is reloaded because all alerts in koala are currently broken.
Instead of trying to fix the creative custom alert function (see first commit), I'll be using [toastr-rails](https://github.com/tylergannon/toastr-rails)
> Fix payment buttons

- app/assets/stylesheets/public.css.scss
- app/views/layouts/public.html.haml
- app/views/public/status/edit.html.haml
- config/locales/nl.yml
> Update studystatus page for bootstrap 4

- app/views/admin/settings/index.html.haml
> Fill useless empty space on admin settings page

- app/assets/stylesheets/application.css
- app/assets/stylesheets/general.css
- app/assets/stylesheets/members.css
- public/403.html
- public/404.html
- public/422.html
- public/500.html
- public/503.html
Fixed small spacing bugs and added a general.css to override yeti values in all pages
> Fixed issue #543

- README.md
Copied 'Running Koala' section from INSTALLING.md to README.md
> Added 'Running Koala' section

- app/views/layouts/partials/_navigation.html.haml
> Keep navbar dropdowns open when on a page in the dropdown

- app/controllers/members/activities_controller.rb
- app/views/members/activities/unavailable.html.haml
- config/locales/en.yml
- config/locales/nl.yml
> Add activity unavailable page

- app/assets/javascripts/admin/activities.js
- app/views/admin/activities/partials/_attendee_table_row.html.haml
- app/views/admin/activities/show.html.haml
- app/views/admin/members/show.html.haml
- app/views/admin/payments/index.html.haml
Closes #565 
hidden no longer exists in bootstrap 4, instead d-none is used
> Use d-none instead of hidden

- app/assets/stylesheets/members/activities.css
- app/views/members/activities/partials/_view.html.haml
- app/views/members/activities/show.html.haml
> Fix member activities page on mobile

- app/assets/stylesheets/page.css
- vendor/assets/stylesheets/yeti.css.scss
At some point the yeti theme was edited directly which was causing some issues while working on #562.
We probably never want to touch anything in `vendor/` directly so this PR reverts `yeti.css.scss` to commit 3ffffa4 (when it was first added).
> Revert yeti.css.scss to 3ffffa4

- app/views/members/home/edit.html.haml
> Move password change button to bottom bar

- app/assets/stylesheets/admin/activities.css
- app/views/admin/activities/index.html.haml
> Always show committee labels

- app/assets/javascripts/members/activities/activities.js
- app/views/members/activities/index.html.haml
- config/locales/en.yml
- config/locales/nl.yml
Added a 'copy ICS' button at the top of the activities page
Fixed issue #538.
> Copy ICS button on activities page

- app/controllers/api/webhook_controller.rb
- app/jobs/mailchimp_job.rb
- app/models/member.rb
- app/views/members/home/edit.html.haml
- config/routes.rb
> Fix mailchimp integration issues

- app/views/admin/activities/index.html.haml
- app/views/admin/activities/show.html.haml
- app/views/admin/apps/checkout.html.haml
- app/views/admin/apps/ideal.html.haml
- app/views/admin/groups/index.html.haml
- app/views/admin/groups/show.html.haml
- app/views/admin/settings/index.html.haml
- app/views/admin/settings/logs.html.haml
> Removed search bar on admin pages that have no direct use for it

- app/controllers/public/home_controller.rb
- app/jobs/mailchimp_job.rb
- app/views/admin/members/edit.html.haml
- app/views/admin/members/new.html.haml
- app/views/admin/members/show.html.haml
- app/views/members/home/edit.html.haml
- config/app.yml
- config/application.rb
Mailchimp config now works on staging
> Move mailchimp config to application.rb

- app/assets/stylesheets/doorkeeper.css
no clue what I did, but it looks good
> fixed scrollbar showing up on login page, closes #593

- app/assets/stylesheets/cards.css
- app/assets/stylesheets/page.css
Added a border to some elements that seemed weird otherwise
> Removed gutters on mobile pages

- app/models/member.rb
> Remove mailchimp user permanently when koala user is deleted

- app/controllers/admin/members_controller.rb
- app/controllers/members/home_controller.rb
- app/controllers/public/home_controller.rb
- app/jobs/mailchimp_job.rb
- app/models/member.rb
- app/views/admin/members/edit.html.haml
- app/views/admin/members/new.html.haml
- app/views/admin/members/show.html.haml
- app/views/members/home/edit.html.haml
Fixed mailchimp errors in case the MAILCHIMP_DATACENTER isn't commented
> Changed nil? to blank?

- app/views/admin/payments/index.html.haml
> Whatsapp icon

- app/views/admin/groups/index.html.haml
- app/views/admin/groups/show.html.haml
> Groups are visible again on mobile

- app/views/members/home/edit.html.haml
> Fixed crashes in member edit page

- app/views/layouts/members.html.haml
- app/views/members/activities/index.html.haml
- config/locales/en.yml
- config/locales/nl.yml
resolves #621 
Removed the bug button and added an external link to svsticky GitHub so if people want to report issues they can do it there
> Removed bug button and made github external links

- app/views/members/home/edit.html.haml
> Fix member edit page breaking on refresh

- .gitignore
- test/controllers/api/activities_controller_test.rb
- test/fixtures/activities.yml
Old branch that was easy to rebase.
This seems useful, please check thoroughly tho
> Update fixtures to be viewable, add Activity + tests

- app/views/members/home/edit.html.haml
- config/locales/en.yml
- config/locales/nl.yml
> Added download attribute to personal data download

- app/assets/javascripts/admin/activities.js
- app/views/admin/activities/partials/_edit.html.haml
> Don't disable participant limit

- app/views/members/activities/show.html.haml
Removed bug button from activity show
> Removed bug button from show activity page

- app/views/admin/members/new.html.haml
Seems this page was still using the old panels, it matches the member edit page now.
Closes #640
> Fix new member form

- app/assets/javascripts/admin/activities.js
> Use correct translation for unpaid message

- app/assets/stylesheets/admin/checkout_products.css
- app/views/admin/apps/products.html.haml
> Product info is now scrollable

- app/controllers/members/home_controller.rb
- app/models/member.rb
- config/locales/devise.en.yml
- config/locales/devise.nl.yml
- db/schema.rb
- db/seeds/members.rb
- db/seeds/users.rb
> 2.3 bug fixes

- app/controllers/admin/activities_controller.rb
- app/views/admin/activities/partials/_edit.html.haml
- app/views/members/activities/show.html.haml
- config/locales/en.yml
- config/locales/nl.yml
- db/migrate/20200505212139_show_participants_activity_option.rb
- db/schema.rb
> Added option to show/hide participants for activities

- db/seeds/members.rb
> Remove special characters from email in seeds

- app/validators/phone_number_validator.rb
- config/locales/nl.yml
> Fix phone number validation

- app/controllers/application_controller.rb
This reverts commit 3d1dcd5383c75ad2ca9aa75a029559864b4e4731.
> Revert "Javascript language now set correctly after login"

- app/assets/javascripts/members/activities/activities.js
- app/assets/javascripts/members/activities/activity.js
- app/assets/stylesheets/members/activities.css
- package.json
- yarn.lock
Updated sweetalert from v1 to v2. This is required for the branch payconiq implementation.
> Update sweetalert to v2

- app/assets/javascripts/admin/members.js
- app/assets/javascripts/intl_tel_number.js
- app/assets/javascripts/intro.js
- app/assets/javascripts/members/main.js
- app/assets/stylesheets/intro.css.scss
- app/views/public/home/index.html.haml
- config/locales/public.en.yml
- config/locales/public.nl.yml
> Intro page changes

- app/assets/javascripts/intro.js
Related to previously merged PR. This removes it from the frontend, so the elfproef should be fully removed from the project now.
> Removed 'Elfproef' from JS

- app/controllers/api/checkout_controller.rb
- app/views/api/checkout/recent.rabl
- config/routes.rb
Also has some minor improvements for the card info. This PR is mainly focussed on the new implementation of Checkout, [magnificent-sloth](https://www.github.com/svsticky/magnificent-sloth).
> Recent products

- app/controllers/admin/checkout_products_controller.rb
> Fix checkout product sorting

- app/assets/javascripts/admin/main.js
- app/assets/stylesheets/admin/main.css
- app/models/member.rb
Fixes several issues with the search bar on admin pages:
Closes #636
> Fix search bar issues

- app/views/layouts/partials/_navigation.html.haml
closes #749 
Kinda baffled by this bug. I'm not sure if this is our fault or something else but this fixes the issue
> Fixed active link

- app/views/members/home/index.html.haml
- config/locales/members.en.yml
- config/locales/members.nl.yml
> Added mongoose info

- config/locales/mailings.en.yml
- config/locales/mailings.nl.yml
Julian wanted to change the text
> Updated gpdr mails

- .hooks/pre-commit
Adds the command i18n-tasks normalize to pre-commit since this is a check might aswell do it every commit so you don't have to fix it afterwards
> Add i18n to pre-commit

- config/locales/en.yml
- config/locales/nl.yml
> Add missing study error translations

- app/assets/javascripts/members/main.js
- app/controllers/api/activities_controller.rb
Closes #454 
This should probably be refactored at some point.
For now I restored the old authorize function `api/activities_controller` and the string formatting function in `members/main.js`.
> Fix participant table update after enrolling

- .hooks/pre-commit
- app/assets/javascripts/admin/main.js
- app/assets/javascripts/members/main.js
- app/assets/stylesheets/admin/main.css
- app/controllers/admin/checkout_products_controller.rb
- app/controllers/admin/members_controller.rb
- app/controllers/api/activities_controller.rb
- app/controllers/api/checkout_controller.rb
- app/controllers/members/home_controller.rb
- app/models/member.rb
- app/views/admin/members/show.html.haml
- app/views/admin/settings/logs.html.haml
- app/views/api/checkout/recent.rabl
- app/views/layouts/partials/_navigation.html.haml
- app/views/members/home/index.html.haml
- config/locales/admin.en.yml
- config/locales/admin.nl.yml
- config/locales/en.yml
- config/locales/mailings.en.yml
- config/locales/mailings.nl.yml
- config/locales/members.en.yml
- config/locales/members.nl.yml
- config/locales/nl.yml
- config/routes.rb
Changelog:
- Fixed some bugs & added compatibility for the new Checkout, [magnificent-sloth](https://github.com/svsticky/magnificent-sloth)
- Added info button in Mongoose transactions div
- You appear immediately after enrolling in the participants list
- Updated the GPDR mailing text
- Added translation normalize to precommit
- Fixed bug related to highlighting in admin menu
- Fixed bug related to sorting products
- Fixed bug related to filtering by tags
- Fixed bugs with study & mailchimp when updating user
> [Release] 2.6.3

- config/locales/mailings.en.yml
- config/locales/mailings.nl.yml
> Sticky Phone explanations

- app/controllers/users/confirmations_controller.rb
> Fix mailconfirmation nil class

- app/controllers/admin/members_controller.rb
- app/controllers/members/home_controller.rb
> Fix changing mailchimp preferences

- app/controllers/admin/members_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/jobs/mailchimp_update_address_job.rb
- app/jobs/mailchimp_update_mail_job.rb
> Update email address in mailchimp when a member's email is changed

- app/controllers/admin/participants_controller.rb
- app/views/layouts/partials/_mail.html.haml
- lib/assets/javascripts/mail.js
Closes #330 
Old issue but still relevant
> Disable 'send' button when list of recipients is empty

- MAILCHIMP.md
- bin/get_mailchimp_interest_ids.sh
Closes #781 
The script automatically finds the MAILCHIMP_TOKEN in your .env file
> Add script to find interest IDs

- db/seeds/activities.rb
> Fixed activity seeding

- app/assets/stylesheets/admin/groups.css
Fixes minor issue that when searching members in the group page they don't get highlighted
> Fix dropdown highlights for group members

- app/assets/stylesheets/members/activities.css
- app/views/members/activities/partials/_view.html.haml
> added on hover effect

- app/assets/javascripts/admin/activities.js
- app/assets/stylesheets/admin/activities.css
- app/controllers/admin/activities_controller.rb
- app/views/admin/activities/partials/_attendee_table_row.html.haml
- app/views/admin/activities/partials/_attendee_table_row_summary.html.haml
- app/views/admin/activities/partials/_edit.html.haml
- app/views/admin/activities/show.html.haml
- config/locales/en.yml
- config/locales/nl.yml
Closes #434
Introduces richer views for activity-participants
> Activity summary views

- app/views/api/checkout/recent.rabl
> Minor changes

- .github/workflows/build.yml
- Gemfile
- Gemfile.lock
- app/controllers/admin/payments_controller.rb
- app/models/group.rb
- config/database.yml
- db/schema.rb
- docker-compose.yml
- gemset.nix
- sample.env
This pull request adds support for postgres on koala.
-- config/database.yml still needs adaptation for when this is to be run on staging or production!
-- iow, still needs some work.
> Add development postgres support, fix hardcoded queries

- app/controllers/admin/payments_controller.rb
- app/controllers/members/payments_controller.rb
- app/javascript/packs/members.js
- app/javascript/src/members/payments.js
- app/models/activity.rb
- app/models/payment.rb
- app/views/admin/activities/partials/_edit.html.haml
- app/views/members/payments/index.html.haml
- db/seeds/activities.rb
- db/seeds/payments.rb
- mongoose returns array instead of hash in export csv
- symbol :successful instead of 'SUCCEEDED' 
- Make activity payment without any activities
- Removed is_payable_before_unenroll_date validation since this should be up to the treasurer not the system
- Updated sample.env
- minor issues
> Payconiq staging issues

- app/views/admin/settings/logs.html.haml
Actually fixes the issue that #822 should've fixed. Probably should've tested this and not made this PR entirely on github.com
> Fixes imppresionist view 

- app/controllers/admin/payments_controller.rb
- app/views/admin/settings/index.html.haml
- app/views/layouts/partials/_search_payments.html.haml
- config/app.yml
- config/locales/en.yml
- config/locales/nl.yml
- db/seeds/payments.rb
Some minor fixes before deploying payconiq onto production
> Fix seeding & Search & Transaction accountancy

- app/controllers/admin/payments_controller.rb
- app/controllers/public/home_controller.rb
- app/views/public/home/index.html.haml
- config/brakeman.ignore
- config/locales/en.yml
Intro site still had old payment system. Has been updated to new payment model with only ideal for now
> Fix intro site and minor translation

- config/brakeman.ignore
brakeman.ignore broke from direct commit to development now build & test workflow fails. This should resolve the issue
> Fix brakeman build

- .github/workflows/build.yml
- README.md
currently refers to the development branch (default)
we don't actively build the master branch atm (maybe we should though)
> updated badge in readme

- app/controllers/members/home_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/views/devise/confirmations/show.html.haml
- app/views/layouts/members.html.haml
- config/locales/devise.en.yml
- config/locales/devise.nl.yml
> Email change enhancements

- app/controllers/public/home_controller.rb
- app/views/public/home/index.html.haml
Made this one pretty quick, have to check it thoroughly soontm
> [High prio] Added teacher mailinglist to intro website

- app/controllers/admin/participants_controller.rb
When merging #861 I created a new bug that made it ignore some validations
> update update function

- lib/tasks/status.rake
> Fix task status:mail query

- app/controllers/members/payments_controller.rb
- config/brakeman.ignore
> Payconiq payment activity listing description implementation: Method call, join_with_char_limit, should be a static call

- default.nix
- nix/node_modules.nix
Closes #877 by pinning the latest version of node2nix that generates files with direct lib calls
> pin node2nix and update generated files

- app/controllers/admin/payments_controller.rb
- config/brakeman.ignore
Not sure why everything was changed from erb to haml but this was broken.
> Whatsapp endpoint broken

- app/controllers/api/webhook_controller.rb
- app/controllers/members/payments_controller.rb
- app/views/members/payments/index.html.haml
- config/brakeman.ignore
- config/routes.rb
Due to having time constraints i've been unable to fully remove payconiq before theirs system stopped. This fix will remove the possibilty of starting a payconiq transaction which is the only breaking part right now. Somebody else can pick up #907 or ill continue it when i have time again
> Payconiq removal hotfix

- nix/node-env.nix
- nix/node.nix
- nix/node_modules.nix
- package.json
> Remove erb-loader and update javascript dependencies

- .github/workflows/build.yml
Part of svsticky/sadserver/issues/333
> update Nix in CI

- app/models/user.rb
- db/migrate/20220221195220_add_deleted_at_to_user.rb
- db/structure.sql
- lib/tasks/admin.rake
add deleted_at column to users this makes it possible to soft delete admin users so they cannot login anymore but the accounts are still there for logging
> add deleted_at to users

- app/views/admin/posts/index.html.haml
This fixes #959 by setting the correct format string
> Show correct time on posts

- .rubocop.yml
- app/controllers/api/internal_controller.rb
- db/structure.sql
Fixes internal api controller and removes erroneous check from rubocop
> Fix internal controller after big rubocop oof (fix rubocop too)

- app/javascript/src/lib/mail.js
- app/views/layouts/partials/_mail.html.haml
- app/views/mailings/participants/inform.html.haml
- config/brakeman.ignore
- config/locales/mailings.nl.yml
fixes #974
This fixes the editor loading code and html, and seems to work alright.
I haven't checked yet how the email look like
> make the activities email send page work with the new editor

- app/views/devise/sessions/new.html.haml
- config/locales/devise.en.yml
- config/locales/devise.nl.yml
> Remove 'remember me' checkbox

- app/controllers/admin/settings_controller.rb
- app/views/admin/settings/index.html.haml
> Do not redirect admins on saving settings, show message instead

- .haml-lint.yml
- app/views/mailings/payment_mailer/requestmail.html.haml
- app/views/mailings/payment_mailer/requestmail.text.haml
- config/locales/mailings.en.yml
- config/locales/mailings.nl.yml
> updated payment email price formatting

- app/controllers/members/participants_controller.rb
- config/locales/en.yml
- config/locales/nl.yml
fixes #994
uses this magic: https://apidock.com/rails/Array/to_sentence
to append arrays together.
> updated participant filter text

- .rubocop.yml
- .rubocop_todo.yml
- app/controllers/admin/home_controller.rb
- app/views/admin/home/index.html.haml
This improves the admin home page controller code by
- Rewriting some functions, making use of existing scopes in the Member model
- Fixing the misspelled `unpayed` function name
- Enabling linters that were previously disabled for this file
The definition of `unpaid` has changed a little bit, bringing it in line with the `payable` attribute on activities.
> updated admin home page controller by simplifying functions and fixing lints

- app/models/activity.rb
- app/views/admin/activities/partials/_edit.html.haml
- app/views/members/activities/partials/_view.html.haml
- config/locales/en.yml
- config/locales/nl.yml
> Fix add calendar

- app/models/activity.rb
Resolves https://github.com/svsticky/constipated-koala/issues/1052
> fix add to calendar incorrect tz

- INSTALLING.md
- default.nix
> Explained (and fixed) dirty environment variables messing up nix

- app/javascript/src/members/activities/activities.js
> Changed webcal into https

- app/controllers/admin/payments_controller.rb
- app/views/admin/members/payment_whatsapp.html.haml
- config/locales/admin.en.yml
- config/locales/admin.nl.yml
- now uses newer wa.me api
- resolve newline before colon
- display message in member-language instead of admin-language
> fix treasurer whatsapp payment reminder

- config/application.rb
- config/initializers/doorkeeper_openid_connect.rb
> doorkeeper: Add full name to OpenID claims

- config/application.rb
- config/initializers/doorkeeper_openid_connect.rb
> doorkeeper: Fix 500 in OAuth endpoint

- app/controllers/admin/activities_controller.rb
- app/javascript/src/admin/activities.js
- app/javascript/src/admin/members.js
- app/views/admin/activities/show.html.haml
- config/routes.rb
Uses the participant.enroll method to enroll each committee member (in activity.js)
> Button to add committe to activity :)

- app/views/members/payments/index.html.haml
Ensures people cannot add funds to their acc
> commented out the whole html.haml block :)

- app/models/activity.rb
> Changed calendar end time to 11:59pm when one isn't set

- app/models/participant.rb
- app/views/members/activities/partials/_view.html.haml
- db/migrate/20240125003700_increase_char_lim_to_member_notes.rb
- db/structure.sql
This is not tested right now. Its late, and I have connection errors...
> Increased char limit to member notes

- app/views/admin/members/show.html.haml
> Remove Mongoose checkout and cards from admin member view

- app/javascript/src/admin/main.js
- app/javascript/src/admin/members.js
- app/views/admin/members/edit.html.haml
- app/views/admin/members/show.html.haml
- app/views/layouts/partials/_search.html.haml
-  'e' (edit)
- 'ctrl+esc' (cancel edit)
- 'ctrl+enter' (save edit)
-  's' || '/' (search)
> Add keybinds to admin members page

- INSTALLING.md
> Never run nix-shell as root

- app/controllers/admin/payments_controller.rb
Not sure how this slipped through tbh...
> Fix: Transaction export was broken

- app/views/layouts/mailer.html.haml
> Update email color to B19 color

- app/models/member.rb
> fix: Hyphens in names of members are deleted

- app/models/activity.rb
> Copy to whatsapp price rounding

- app/assets/stylesheets/members/activities.css
- app/controllers/members/activities_controller.rb
- app/views/members/activities/index.html.haml
- config/locales/members.en.yml
- config/locales/members.nl.yml
Closes #1138
Maybe the webcal links should be moved because of this
For reviewer: I am thinking about maybe changing the Dutch names and I'm not 100% happy with the design of the top bar now
> feat: visibility options on activity page

- app/controllers/members/activities_controller.rb
- app/views/members/activities/index.html.haml
> fix: Error only shows when no activities exist

- app/views/layouts/members.html.haml
- config/locales/members.en.yml
- config/locales/members.nl.yml
> Add committeeclash to the external link list
